// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcqKazfjWXQUEVlQBAb0WeWuXc3ywVGcE',
    appId: '1:295257017311:web:3bbc51697e3312f224926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    authDomain: 'rentapp-7a3ec.firebaseapp.com',
    storageBucket: 'rentapp-7a3ec.firebasestorage.app',
    measurementId: 'G-PBS2457X32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3L-1cami7weVTtJG_FYjrxYtGNTlXqoE',
    appId: '1:295257017311:android:872169cb00c0ffee24926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    storageBucket: 'rentapp-7a3ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucDc_LcY6whcwsXQlT8nDwI9oVqU_mqk',
    appId: '1:295257017311:ios:5bf302fc2133beca24926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    storageBucket: 'rentapp-7a3ec.firebasestorage.app',
    iosClientId: '295257017311-66ch9d4k7fch5q40q0tdmpcj4d4o53jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucDc_LcY6whcwsXQlT8nDwI9oVqU_mqk',
    appId: '1:295257017311:ios:5bf302fc2133beca24926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    storageBucket: 'rentapp-7a3ec.firebasestorage.app',
    iosClientId: '295257017311-66ch9d4k7fch5q40q0tdmpcj4d4o53jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDLapHqrC59W-q1ct9yid5hKGPEE7OvQM',
    appId: '1:295257017311:web:3aa3f3b2b89d3b3424926a',
    messagingSenderId: '295257017311',
    projectId: 'rentapp-7a3ec',
    authDomain: 'rentapp-7a3ec.firebaseapp.com',
    storageBucket: 'rentapp-7a3ec.firebasestorage.app',
    measurementId: 'G-P6NCSP0HCS',
  );
}
